added stages/functions to master_reduce

diff --git a/pyDRP/master_reduce b/pyDRP/master_reduce
--- a/pyDRP/master_reduce
+++ b/pyDRP/master_reduce
@@ -3,10 +3,12 @@
 # supply regions files
 # needs to be in the same directory as raw data! -- update this!
 
-echo "Hello!"
+echo "Hello! 😎"
 echo "Welcome to the CAREFUL version of the KCWI python DRP!"
 echo "Please make sure you have run 'conda activate kcwidrp' before proceeding"
+echo "Please specify RAW_DIR (-d) and obj.txt file (-o)"
 
+set -e #make sure we don't proceed if not in kcwidrp environment
 
 
 while getopts d:ho:s: optval
@@ -16,129 +18,163 @@ do
 		 d) dir="$OPTARG";;
 		 # st) STAGE="$OPTARG";;
 		 o) obj=(); while IFS= read -r line; do obj+=("$line"); done <$OPTARG;;
-		 # s) std+=({$OPTARG});;
+		 s) IFS=, # split on (tres) commas
+		    stages=($OPTARG);;
 		 *) echo "master_reduce -h for help"; exit -1;;
    esac
 done
 # shift $((OPTIND-1));
 
 if [ $HELP ]; then
-	echo "master_reduce -d RAW_DIR -o OBJECTS -s STDS [-h]"
+	echo "master_reduce -d RAW_DIR -o obj.txt  -s stage1drp,stage1plus,... [-h]"
 	echo "KCWI python DRP + extra intermediate steps"
 	echo "-d RAW_DIR  directory with raw data"
 	# echo "-st STAGE   which stage of the reduction to do?"
-	echo "-o OBJECTS  list of science objects e.g. 43..54"
-	echo "-s STDS     list of standard stars e.g. 54..59"
+	echo "-o obj.txt  name of text file in RAW_DIR with list of science objects e.g. \nkb181110_00061 \nkb181110_00062 \n.\n.\n."
+	echo "-s STAGES   list of stages to run (default: main) e.g. \nstage1drp,stage1plus,stage2drp \nor \nstage1plusToEnd"
 	echo "-h .......  help (display)"
 	exit -1
 fi
 
-# Example: ~/Software/kcwi/pyDRP/master_reduce -d /Volumes/Data/Documents/Chuck/Observing/2022may28 -o 071..092 -s 061..070 -s 093..101
+
+stage1drp () {
+  echo ""
+  echo "Stage 1"
+  reduce_kcwi -f kb*.fits -g -st 1
+  echo "Stage 1 is Done!"
+}
+
+stage1plus () {
+  # make *_smsk.fits files
+  for i in $obj
+  do
+  	python ~/Software/KCWI_DRP/kcwidrp/scripts/kcwi_masksky_ds9.py redux/${i}_intf.fits redux/$i.reg;
+  done
+
+  mkdir -p redux/stage5_nomask
+  mv redux/*intk.fits redux/*sky.fits redux/stage5_nomask
+
+  sed -i '' '/sky/d' kcwi.proc #remove sky
+  sed -i '' '/intk/d' kcwi.proc #remove intk
+
+  #make kcwi.sky file
+  for i in $obj
+  do
+  	echo ${i}.fits ${i}.fits redux/${i}_smsk.fits
+  done >> kcwi.sky
+}
+
+stage2drp () {
+  echo "Stage 2"
+  reduce_kcwi -f kb*.fits -g -st 2
+  echo "Stage 2 is Done!"
+}
 
 
+stage2plus () {
+  #note fitsheader needs astropy!
+
+  all=($(fitsheader redux/kb*_icube.fits --extension 0 -f -k IMTYPE | grep OBJECT | sed 's/_icube.*//' | sed 's$redux/$$'))
+
+  python ~/Software/kcwi/pyDRP/kcwi_flatten_cube.py redux/${^obj}_icube.fits #make *_icube_2d.fits files
+  python ~/Software/kcwi/pyDRP/kcwi_collapse.py redux/${^all}_icube.fits #make *_icube.thum.fits files
+
+  python ~/Software/kcwi/pro/kcwi_makemask_medfilter_nik.py redux #make *_icube_2d.mask.fits and *_icube.mask.fits files
+
+  #make a backup of *icube.fits files
+  mkdir -p redux/pre_med_filt
+  cp redux/*icube.fits redux/pre_med_filt
+
+  python ~/Software/kcwi/pyDRP/kcwi_medfilter.py redux/${^all}_icube.fits #median filter
+
+  # remove SKY and OBJECT from kcwi.proc
+  sed -i '' '/OBJECT/d' kcwi.proc
+  sed -i '' '/SKY/d' kcwi.proc
+}
 
 
+stage3drp () {
+  echo "Stage 3"
+  echo "Note this stage will require some human intervention..."
+  reduce_kcwi -f kb*.fits -g -st 3
+  echo "Stage 3 is Done!"
+}
 
+stage3plus () {
+  mkdir -p fluxcal
+  cd fluxcal
+  ls ../redux/*invsens*fits | column -c 1 >> med_bl.list
+
+  std=($(ls ../redux/*invsens*fits | xargs -n 1 basename | sed 's/_invsens.*//'))
+
+  python ~/Software/kcwi/pyDRP/kcwi_combinestd.py med_bl.list
+  cp med_bl_invsens.fits ../redux #this should be fixed?
+  cd ../ #perhaps there's a better way to do this
+
+  #clean proc table
+  sed -i '' '/ea/d' kcwi.proc
+  sed -i '' '/icubes/d' kcwi.proc
+
+  for i in $std
+  do
+  	sed -i '' "s/${i}.fits/        med_bl.fits/g" kcwi.proc
+  done
+
+  mkdir -p redux/pre_std_star_stack
+  cp redux/*icubes.fits redux/pre_std_star_stack
+}
+
+stage4drp () {
+  echo "Stage 4"
+  reduce_kcwi -f kb*.fits -g -st 3
+  echo "Stage 4 is Done!"
+  echo "First Part of Reduction Complete"
+  echo "Now onto stacking??"
+}
+
+
+main () {
+	stage1drp
+	stage1plus
+
+	stage2drp
+	stage2plus
+
+	stage3drp
+	stage3plus
+
+	stage4drp
+}
+
+# assume primary failure point is during stage1drp
+stage1plusToEnd () {
+	stage1plus
+
+	stage2drp
+	stage2plus
+
+	stage3drp
+	stage3plus
+
+	stage4drp
+}
+
+### Beginning of Program ###
 
 # dir=/Volumes/Data/Documents/Chuck/KCWI_DRP/pyDRP/q0933-MD75_bash_test-2/
 cd $dir
-
+echo ""
 echo "We are in $dir"
 echo ""
+echo "Science Objects:"
+echo $obj | xargs -n 1
 
-# echo ""
-# echo "Stage 1"
-
-echo "Science Objects: $obj"
-# echo "Standard Stars: $std"
-
-# obj=({53..71}) #science target file numbers
-# std=({72..74}) #standard star file numbers
-# all=("${obj[@]}" "${std[@]}") #union of obj and std
-# echo "All Objects: $all"
-
-echo ""
-echo "Stage 1"
-
-# echo {${obj[1]}..${obj[2]}}
-#conda activate kcwidrp
-
-set -e #make sure we don't proceed if not in kcwidrp environment
-
-
-reduce_kcwi -f kb*.fits -g -st 1
-echo "Stage 1 is Done!"
-
-# make *_smsk.fits files
-for i in $obj
-do
-	python ~/Software/KCWI_DRP/kcwidrp/scripts/kcwi_masksky_ds9.py redux/${i}_intf.fits redux/$i.reg;
-done
-
-mkdir redux/stage5_nomask
-mv redux/*intk.fits redux/*sky.fits redux/stage5_nomask
-
-sed -i '' '/sky/d' kcwi.proc #remove sky
-sed -i '' '/intk/d' kcwi.proc #remove intk
-
-#make kcwi.sky file
-for i in $obj
-do
-	echo ${i}.fits ${i}.fits redux/${i}_smsk.fits
-done >> kcwi.sky
-
-echo "Stage 2"
-reduce_kcwi -f kb*.fits -g -st 2
-echo "Stage 2 is Done!"
-
-#note fitsheader needs astropy!
-
-all=($(fitsheader redux/kb*_icube.fits --extension 0 -f -k IMTYPE | grep OBJECT | sed 's/_icube.*//' | sed 's$redux/$$'))
-
-python ~/Software/kcwi/pyDRP/kcwi_flatten_cube.py redux/${^obj}_icube.fits #make *_icube_2d.fits files
-python ~/Software/kcwi/pyDRP/kcwi_collapse.py redux/${^all}_icube.fits #make *_icube.thum.fits files
-
-python ~/Software/kcwi/pro/kcwi_makemask_medfilter_nik.py redux #make *_icube_2d.mask.fits and *_icube.mask.fits files
-
-#make a backup of *icube.fits files
-mkdir redux/pre_med_filt
-cp redux/*icube.fits redux/pre_med_filt
-
-python ~/Software/kcwi/pyDRP/kcwi_medfilter.py redux/${^all}_icube.fits #median filter
-
-# remove SKY and OBJECT from kcwi.proc
-sed -i '' '/OBJECT/d' kcwi.proc
-sed -i '' '/SKY/d' kcwi.proc
-
-echo "Stage 3"
-reduce_kcwi -f kb*.fits -g -st 3
-echo "Stage 3 is Done!"
-
-mkdir fluxcal
-cd fluxcal
-ls ../redux/*invsens*fits | column -c 1 >> med_bl.list
-
-std=($(ls ../redux/*invsens*fits | xargs -n 1 basename | sed 's/_invsens.*//'))
-
-python ~/Software/kcwi/pyDRP/kcwi_combinestd.py med_bl.list
-cp med_bl_invsens.fits ../redux #this should be fixed?
-cd ../ #perhaps there's a better way to do this
-
-#clean proc table
-sed -i '' '/ea/d' kcwi.proc
-sed -i '' '/icubes/d' kcwi.proc
-
-for i in $std
-do
-	sed -i '' "s/${i}.fits/        med_bl.fits/g" kcwi.proc
-done
-
-mkdir redux/pre_std_star_stack
-cp redux/*icubes.fits redux/pre_std_star_stack
-
-echo "Stage 4"
-reduce_kcwi -f kb*.fits -g -st 3
-echo "Stage 4 is Done!"
-
-echo "First Part of Reduction Complete"
-echo "Now onto stacking??"
+if [ $stages ]; then
+  echo ""
+  echo "Stages to Do:"
+  for func in "${=stages}"; do echo ${func}; done;
+  echo ""
+	for func in "${=stages}"; do ${func}; done;
+else
+	main
+fi
